Changes to Loader and Extractor classes
dpalencia/marsvision pull request #6
Opened 2020-10-08 23:41 UTC by dpalencia

2020-10-21 15:22 UTC, michaelmunje requested changes
Overall looks good. Added some fine-grained feedback. We should ensure that each function of the python package contains docstrings as well as type hinting, where applicable. 

The testing suite does not need this.

2020-10-21 15:22 UTC, michaelmunje commented on setup.py
> +    author="Daniel Palencia",
Before we forget, we may want to add the other group members as authors, as well as myself. Also, we should probably make a github group and place the repo inside of that.

2020-10-21 15:22 UTC, michaelmunje commented on marsvision/utilities/DataLoader.py
> +        for(root, dirs, files) in walk:
Does not need to be inside a tuple here.

2020-10-21 15:22 UTC, michaelmunje commented on marsvision/utilities/DataLoader.py
> +                    images.append(cv2.imread(os.path.join(root, file)))
Note that sometimes if opencv tries to read a corrupted file or one with the wrong path it may return None for imread. Therefore, you should check if it returns None before appending to this list of images.

2020-10-21 15:22 UTC, michaelmunje commented on marsvision/utilities/DataLoader.py
> +        detector  = cv2.ORB_create()
This should be in the feature extractor class containing the keypoint functions. We can include a parameter for the constructor such as "detector_type" as a string and have if-else statements to initialize the corresponding detector.

2020-10-21 15:22 UTC, michaelmunje commented on marsvision/utilities/DataLoader.py
> +        df.to_csv(out_file, mode="a", header=False, index=False)
I don't think we should use the append mode and should just create a new file each time to avoid duplicate entries.

2020-10-21 15:22 UTC, michaelmunje commented on test/test_feature_extractor.py
> +from marsvision.pipeline import FeatureExtractor as fe
We probably do not want to do this just to ensure our code is readable. It is fine since our package is small but when there are more submodules this might become confusing.

2020-10-21 15:22 UTC, michaelmunje commented on test/test_feature_extractor.py
> +        self.expected_features = [
More proper would be to make this a file and load it as a numpy array. Look into the .npy file extension if you can.

https://numpy.org/doc/stable/reference/generated/numpy.save.html
https://numpy.org/doc/stable/reference/generated/numpy.load.html

2020-10-27 18:35 UTC, dpalencia commented on marsvision/pipeline/FeatureExtractor.py
> +        return [(round(keypoint.pt[0]), round(keypoint.pt[1])) for keypoint in keypoints]
They're being rounded because we need to use integers for the slice indices in the select_roi function.

2020-10-27 18:35 UTC, dpalencia commented on extract_data.sh
> +python -m marsvision.utilities.DataLoader --i="miscal" --c="no_dust" --f=True
Updated this script to invoke the python script directly and use default parameters.

2020-10-27 18:36 UTC, dpalencia commented on marsvision/pipeline/FeatureExtractor.py
> +        radius = 20
Turned this into a class member.

2020-10-27 18:36 UTC, dpalencia commented on marsvision/pipeline/FeatureExtractor.py
> +    def extract_means_keypoints(self, img):
Renamed to get_means_from_keypoints

2020-10-27 18:36 UTC, dpalencia commented on marsvision/pipeline/FeatureExtractor.py
> +    def extract_features(img):
Separated this function into a static class; renamed the feature extractor with keypoints to KeyPointFeatureExtractor. Will keep it off to the side for now (since we're not actually using it at the moment). Also updated the KeyPointFeatureExtractor to use the this function--definitely cleans up the code a bit

2020-10-27 18:37 UTC, dpalencia commented on setup.py
> +    author="Daniel Palencia",
Added the rest of the team as authors.

2020-11-04 18:02 UTC, dpalencia commented on marsvision/utilities/DataLoader.py
> +        detector  = cv2.ORB_create()
Added as a member variable

2020-11-04 19:08 UTC, dpalencia commented on marsvision/utilities/DataLoader.py
> +        df.to_csv(out_file, mode="a", header=False, index=False)
Removed append mode; instead, the script can be run once and classes are set as folder names if no class name is passed into the DataLoader constructor.

2020-11-05 19:13 UTC, merged